"""
Team database for the tactical board.

This is a static, embedded "database" (a plain Python data structure) --
the right choice for a client-side app that ships as static files on
GitHub Pages, where there's no server to host a real database. If this
project ever grows a backend, this module is the natural place to swap
in a real DB/API call: everything else in the app just consumes the
TEAMS list and doesn't care where it came from.

Teams here are original/fictional (names and kits), not real clubs --
avoids any trademark/likeness issues while keeping the same data shape
you'd use for real squads.

Each team has:
  - id, name
  - "kits": a list of outfield uniforms the user can pick between.
      Each kit = { "name": str, "pattern": one of
                   "solid" | "stripes" | "hoops" | "halves",
                   "colors": [color] for solid, or [color1, color2]
                   for the two-color patterns }
  - "gk_kit": a single dedicated goalkeeper uniform (same shape as a kit),
      always used for whichever token occupies the GK slot.
  - "squad": a roster of players, more than the 11 that fit on the pitch,
      so the "pick a player" list has real options.
      Each player = { "number": int, "name": str, "position": one of
                      "GK" | "DF" | "MF" | "FW" }
"""

TEAMS = [
    {
        "id": 'fc_porto',
        "name": 'FC Porto',
        "kits": [
            {"name": 'Home', "pattern": 'vertical-2-stripes_3_col-2', "colors": [(39, 62, 124), (229, 228, 226)]},
            {"name": 'Away', "pattern": 'solid', "colors": [(231, 137, 122)]},
            {"name": 'Third', "pattern": 'solid', "colors": [(255, 255, 255)]},
        ],
        "gk_kit": {"name": 'GK', "pattern": 'solid', "colors": [(240, 196, 25)]},
        "squad": [
            {"number": 14, "name": 'Cláudio Ramos', "position": 'GK'},
            {"number": 24, "name": 'João Costa', "position": 'GK'},
            {"number": 51, "name": 'Diogo Fernandes', "position": 'GK'},
            {"number": 99, "name": 'Diogo Costa', "position": 'GK'},
            {"number": 20, "name": 'Alberto Costa', "position": 'DF'},
            {"number": 46, "name": 'Pedro Lima', "position": 'DF'},
            {"number": 52, "name": 'Martim Fernandes', "position": 'DF'},
            {"number": 3, "name": 'Thiago Silva', "position": 'DF'},
            {"number": 3, "name": 'Zé Pedro', "position": 'DF'},
            {"number": 4, "name": 'Jakub Kiwior', "position": 'DF'},
            {"number": 5, "name": 'Jan Bednarek', "position": 'DF'},
            {"number": 18, "name": 'Nehuén Pérez', "position": 'DF'},
            {"number": 21, "name": 'Dominik Prpić', "position": 'DF'},
            {"number": 73, "name": 'Gabriel Brás', "position": 'DF'},
            {"number": 12, "name": 'Zaidu Sanusi', "position": 'DF'},
            {"number": 74, "name": 'Francisco Moura', "position": 'DF'},
            {"number": 13, "name": 'Pablo Rosario', "position": 'MF'},
            {"number": 22, "name": 'Alan Varela', "position": 'MF'},
            {"number": 42, "name": 'Seko Fofana', "position": 'MF'},
            {"number": 6, "name": 'Stephen Eustáquio', "position": 'MF'},
            {"number": 8, "name": 'Victor Froholdt', "position": 'MF'},
            {"number": 15, "name": 'Vasco Sousa', "position": 'MF'},
            {"number": 58, "name": 'Tiago Silva', "position": 'MF'},
            {"number": 66, "name": 'Bernardo Lima', "position": 'MF'},
            {"number": 68, "name": 'André Oliveira', "position": 'MF'},
            {"number": 92, "name": 'João Teixeira', "position": 'MF'},
            {"number": 10, "name": 'Gabri Veiga', "position": 'MF'},
            {"number": 86, "name": 'Rodrigo Mora', "position": 'MF'},
            {"number": 7, "name": 'William Gomes', "position": 'FW'},
            {"number": 11, "name": 'Pepê', "position": 'FW'},
            {"number": 49, "name": 'Gonçalo Sousa', "position": 'FW'},
            {"number": 59, "name": 'Tiago Andrade', "position": 'FW'},
            {"number": 72, "name": 'André Miranda', "position": 'FW'},
            {"number": 87, "name": 'Bryan Caicedo', "position": 'FW'},
            {"number": 26, "name": 'Luuk de Jong', "position": 'FW'},
            {"number": 29, "name": 'Terem Moffi', "position": 'FW'},
            {"number": 9, "name": 'Samu', "position": 'FW'},
            {"number": 27, "name": 'Deniz Gül', "position": 'FW'},
            {"number": 75, "name": 'Yann Karamoh', "position": 'FW'},
            {"number": 17, "name": 'Borja Sainz', "position": 'FW'},
            {"number": 47, "name": 'Ángel Alarcón', "position": 'FW'},
            {"number": 77, "name": 'Oskar Pietuszewski', "position": 'FW'},
        ],
    },
    {
        "id": 'sporting',
        "name": 'Sporting',
        "kits": [
            {"name": 'Home', "pattern": 'horizontal-5-stripes_1_col-2', "colors": [(250, 250, 250), (0, 112, 60)]},
            {"name": 'Away', "pattern": 'solid', "colors": [(255, 255, 255), (0, 107, 69)]},
            {"name": 'Third', "pattern": 'solid', "colors": [(15, 20, 18), (0, 115, 76)]},
        ],
        "gk_kit": {"name": 'GK', "pattern": 'solid', "colors": [(240, 196, 25)]},
        "squad": [
            {"number": 1, "name": 'Rui Silva', "position": 'GK'},
            {"number": 12, "name": 'João Virgínia', "position": 'GK'},
            {"number": 41, "name": 'Diego Callai', "position": 'GK'},
            {"number": 13, "name": 'Georgios Vagiannidis', "position": 'DF'},
            {"number": 22, "name": 'Iván Fresneda', "position": 'DF'},
            {"number": 47, "name": 'Ricardo Esgaio', "position": 'DF'},
            {"number": 49, "name": 'Rômulo Júnior', "position": 'DF'},
            {"number": 3, "name": 'Jeremiah St. Juste', "position": 'DF'},
            {"number": 6, "name": 'Zeno Debast', "position": 'DF'},
            {"number": 25, "name": 'Gonçalo Inácio', "position": 'DF'},
            {"number": 26, "name": 'Ousmane Diomande', "position": 'DF'},
            {"number": 43, "name": 'João Muniz', "position": 'DF'},
            {"number": 72, "name": 'Eduardo Quaresma', "position": 'DF'},
            {"number": 2, "name": 'Matheus Reis', "position": 'DF'},
            {"number": 20, "name": 'Maxi Araújo', "position": 'DF'},
            {"number": 91, "name": 'Ricardo Mangas', "position": 'DF'},
            {"number": 42, "name": 'Morten Hjulmand', "position": 'MF'},
            {"number": 60, "name": 'Rayan Lucas', "position": 'MF'},
            {"number": 73, "name": 'Eduardo Felicíssimo', "position": 'MF'},
            {"number": 5, "name": 'Hidemasa Morita', "position": 'MF'},
            {"number": 14, "name": 'Giorgi Kochorashvili', "position": 'MF'},
            {"number": 23, "name": 'Daniel Bragança', "position": 'MF'},
            {"number": 52, "name": 'João Simões', "position": 'MF'},
            {"number": 10, "name": 'Geny Catamo', "position": 'FW'},
            {"number": 17, "name": 'Francisco Trincão', "position": 'FW'},
            {"number": 31, "name": 'Luís Guilherme', "position": 'FW'},
            {"number": 63, "name": 'Chris Grombahi', "position": 'FW'},
            {"number": 70, "name": 'Salvador Blopa', "position": 'FW'},
            {"number": 9, "name": 'Conrad Harder', "position": 'FW'},
            {"number": 28, "name": 'Rodrigo Ribeiro', "position": 'FW'},
            {"number": 89, "name": 'Fotis Ioannidis', "position": 'FW'},
            {"number": 90, "name": 'Rafael Nel', "position": 'FW'},
            {"number": 97, "name": 'Luis Suárez', "position": 'FW'},
            {"number": 7, "name": 'Geovany Quenda', "position": 'FW'},
            {"number": 8, "name": 'Pedro Gonçalves', "position": 'FW'},
            {"number": 11, "name": 'Nuno Santos', "position": 'FW'},
            {"number": 15, "name": 'Souleymane Faye', "position": 'FW'},
            {"number": 27, "name": 'Alisson Santos', "position": 'FW'},
            {"number": 58, "name": 'Flávio Gonçalves', "position": 'FW'},
        ],
    },
    {
        "id": 'benfica',
        "name": 'Benfica',
        "kits": [
            {"name": 'Home', "pattern": 'solid', "colors": [(153, 0, 18), (229, 228, 226)]},
            {"name": 'Away', "pattern": 'solid', "colors": [(174, 173, 169), (0, 0, 0)]},
            {"name": 'Third', "pattern": 'solid', "colors": [(255, 255, 255), (147, 2, 2)]},
        ],
        "gk_kit": {"name": 'GK', "pattern": 'solid', "colors": [(240, 196, 25)]},
        "squad": [
            {"number": 1, "name": 'Anatoliy Trubin', "position": 'GK'},
            {"number": 24, "name": 'Samuel Soares', "position": 'GK'},
            {"number": 50, "name": 'Diogo Ferreira', "position": 'GK'},
            {"number": 51, "name": 'Arnas Voitinovicius', "position": 'GK'},
            {"number": 6, "name": 'Alexander Bah', "position": 'DF'},
            {"number": 17, "name": 'Amar Dedić', "position": 'DF'},
            {"number": 58, "name": 'Daniel Banjaqui', "position": 'DF'},
            {"number": 71, "name": 'Leandro Santos', "position": 'DF'},
            {"number": 4, "name": 'António Silva', "position": 'DF'},
            {"number": 30, "name": 'Nicolás Otamendi', "position": 'DF'},
            {"number": 44, "name": 'Tomás Araújo', "position": 'DF'},
            {"number": 64, "name": 'Gonçalo Oliveira', "position": 'DF'},
            {"number": 66, "name": 'Joshua Wynder', "position": 'DF'},
            {"number": 3, "name": 'Rafa Obrador', "position": 'DF'},
            {"number": 15, "name": 'Sidny Cabral', "position": 'DF'},
            {"number": 26, "name": 'Samuel Dahl', "position": 'DF'},
            {"number": 62, "name": 'José Neto', "position": 'DF'},
            {"number": 5, "name": 'Enzo Barrenechea', "position": 'MF'},
            {"number": 16, "name": 'Manu Silva', "position": 'MF'},
            {"number": 61, "name": 'Florentino Luís', "position": 'MF'},
            {"number": 8, "name": 'Fredrik Aursnes', "position": 'MF'},
            {"number": 18, "name": 'Leandro Barreiro', "position": 'MF'},
            {"number": 20, "name": 'Richard Ríos', "position": 'MF'},
            {"number": 68, "name": 'João Veloso', "position": 'MF'},
            {"number": 86, "name": 'Diogo Prioste', "position": 'MF'},
            {"number": 88, "name": 'Tiago Freitas', "position": 'MF'},
            {"number": 10, "name": 'Georgiy Sudakov', "position": 'MF'},
            {"number": 77, "name": 'Gonçalo Moreira', "position": 'MF'},
            {"number": 11, "name": 'Dodi Lukebakio', "position": 'FW'},
            {"number": 25, "name": 'Gianluca Prestianni', "position": 'FW'},
            {"number": 47, "name": 'Tiago Gouveia', "position": 'FW'},
            {"number": 67, "name": 'Rodrigo Rêgo', "position": 'FW'},
            {"number": 84, "name": 'João Rego', "position": 'FW'},
            {"number": 27, "name": 'Rafa Silva', "position": 'FW'},
            {"number": 9, "name": 'Franjo Ivanovic', "position": 'FW'},
            {"number": 14, "name": 'Vangelis Pavlidis', "position": 'FW'},
            {"number": 39, "name": 'Henrique Araújo', "position": 'FW'},
            {"number": 72, "name": 'Anísio Cabral', "position": 'FW'},
            {"number": 7, "name": 'Kerem Aktürkoğlu', "position": 'FW'},
            {"number": 7, "name": 'Bruma', "position": 'FW'},
            {"number": 21, "name": 'Andreas Schjelderup', "position": 'FW'},
            {"number": 90, "name": 'Ivan Lima', "position": 'FW'},
        ],
    },
    {
        "id": 'sc_braga',
        "name": 'SC Braga',
        "kits": [
            {"name": 'Home', "pattern": 'sleeves_plain_2_col-2', "colors": [(173, 24, 20), (229, 228, 226)]},
            {"name": 'Away', "pattern": 'solid', "colors": [(255, 255, 255), (173, 24, 20)]},
            {"name": 'Third', "pattern": 'solid', "colors": [(120, 25, 133)]},
        ],
        "gk_kit": {"name": 'GK', "pattern": 'solid', "colors": [(240, 196, 25)]},
        "squad": [
            {"number": 56, "name": 'Romário Cunha', "position": 'GK'},
            {"number": 1, "name": 'Lukas Hornicek', "position": 'GK'},
            {"number": 12, "name": 'Tiago Sá', "position": 'GK'},
            {"number": 36, "name": 'Alaa Bellaarouch', "position": 'GK'},
            {"number": 78, "name": 'João Carvalho', "position": 'GK'},
            {"number": 13, "name": 'Rodrigo Silva', "position": 'DF'},
            {"number": 96, "name": 'Afonso Sousa', "position": 'DF'},
            {"number": 2, "name": 'Víctor Gómez', "position": 'DF'},
            {"number": 62, "name": 'Nuno Matos', "position": 'DF'},
            {"number": 15, "name": 'Paulo Oliveira', "position": 'DF'},
            {"number": 3, "name": 'Robson Bambu', "position": 'DF'},
            {"number": 4, "name": 'Sikou Niakaté', "position": 'DF'},
            {"number": 14, "name": 'Gustaf Lagerbielke', "position": 'DF'},
            {"number": 26, "name": 'Bright Arrey-Mbi', "position": 'DF'},
            {"number": 37, "name": 'Adrian Barisic', "position": 'DF'},
            {"number": 53, "name": 'Jónatas Noro', "position": 'DF'},
            {"number": 81, "name": 'Fodé Pascoal', "position": 'DF'},
            {"number": 5, "name": 'Leonardo Lelo', "position": 'DF'},
            {"number": 6, "name": 'Vitor Carvalho', "position": 'MF'},
            {"number": 41, "name": 'Yanis da Rocha', "position": 'MF'},
            {"number": 17, "name": 'Gabriel Moscardo', "position": 'MF'},
            {"number": 27, "name": 'Florian Grillitsch', "position": 'MF'},
            {"number": 8, "name": 'João Moutinho', "position": 'MF'},
            {"number": 29, "name": 'Gorby Baptiste', "position": 'MF'},
            {"number": 34, "name": 'Demir Tiknaz', "position": 'MF'},
            {"number": 50, "name": 'Diego Rodrigues', "position": 'MF'},
            {"number": 90, "name": 'Luisinho', "position": 'MF'},
            {"number": 92, "name": 'António Gil', "position": 'MF'},
            {"number": 33, "name": 'João Marques', "position": 'MF'},
            {"number": 70, "name": 'Rodrigo Silva', "position": 'FW'},
            {"number": 67, "name": 'Afonso Patrão', "position": 'FW'},
            {"number": 80, "name": 'João Vasconcelos', "position": 'FW'},
            {"number": 10, "name": 'Rodrigo Zalazar', "position": 'FW'},
            {"number": 7, "name": 'Roger Fernandes', "position": 'FW'},
            {"number": 20, "name": 'Mario Dorgeles', "position": 'FW'},
            {"number": 9, "name": 'Amine El Ouazzani', "position": 'FW'},
            {"number": 11, "name": 'Samy Merheg', "position": 'FW'},
            {"number": 18, "name": 'Pau Victor', "position": 'FW'},
            {"number": 39, "name": 'Fran Navarro', "position": 'FW'},
            {"number": 11, "name": 'Ismaël Gharbi', "position": 'FW'},
            {"number": 21, "name": 'Ricardo Horta', "position": 'FW'},
            {"number": 72, "name": 'João Aragão', "position": 'FW'},
            {"number": 77, "name": 'Gabri Martínez', "position": 'FW'},
            {"number": 95, "name": 'Sandro Vidigal', "position": 'FW'},
        ],
    },
    {
        "id": 'fc_famalic_o',
        "name": 'FC Famalicão',
        "kits": [
            {"name": 'Home', "pattern": 'solid', "colors": [(255, 255, 255), (35, 43, 70)]},
            {"name": 'Away', "pattern": 'solid', "colors": [(32, 47, 90), (254, 205, 0)]},
        ],
        "gk_kit": {"name": 'GK', "pattern": 'solid', "colors": [(240, 196, 25)]},
        "squad": [
            {"number": 1, "name": 'Ivan Zlobin', "position": 'GK'},
            {"number": 22, "name": 'Gabriel Cabral', "position": 'GK'},
            {"number": 25, "name": 'Lazar Carević', "position": 'GK'},
            {"number": 90, "name": 'Hugo Cunha', "position": 'GK'},
            {"number": 2, "name": 'Gustavo Garcia', "position": 'DF'},
            {"number": 17, "name": 'Rodrigo Pinheiro', "position": 'DF'},
            {"number": 13, "name": 'Renan Santana', "position": 'DF'},
            {"number": 48, "name": 'Rafael Venâncio', "position": 'DF'},
            {"number": 3, "name": 'Léo Realpe', "position": 'DF'},
            {"number": 16, "name": 'Justin de Haas', "position": 'DF'},
            {"number": 30, "name": 'Vojin Serafimovic', "position": 'DF'},
            {"number": 36, "name": 'Matheus Mattara', "position": 'DF'},
            {"number": 55, "name": 'Ibrahima Ba', "position": 'DF'},
            {"number": 5, "name": 'Rafa Soares', "position": 'DF'},
            {"number": 28, "name": 'Pedro Bondo', "position": 'DF'},
            {"number": 54, "name": 'Lamine Beye', "position": 'MF'},
            {"number": 6, "name": 'Tom van de Looi', "position": 'MF'},
            {"number": 8, "name": 'Marcos Peña', "position": 'MF'},
            {"number": 14, "name": 'Mathias de Amorim', "position": 'MF'},
            {"number": 15, "name": 'Otar Mamageishvili', "position": 'MF'},
            {"number": 47, "name": 'Gonzalo Pastor', "position": 'MF'},
            {"number": 19, "name": 'Rodrigo Ribeiro', "position": 'MF'},
            {"number": 20, "name": 'Gustavo Sá', "position": 'MF'},
            {"number": 18, "name": 'Roméo Beney', "position": 'FW'},
            {"number": 23, "name": 'Gil Dias', "position": 'FW'},
            {"number": 80, "name": 'Pedro Santos', "position": 'FW'},
            {"number": 9, "name": 'Umar Abubakar', "position": 'FW'},
            {"number": 12, "name": 'Simon Elisor', "position": 'FW'},
            {"number": 21, "name": 'Yassir Zabiri', "position": 'FW'},
            {"number": 91, "name": 'Rudi Almeida', "position": 'FW'},
            {"number": 10, "name": 'Rochinha', "position": 'FW'},
            {"number": 77, "name": 'Antoine Joujou', "position": 'FW'},
            {"number": 7, "name": 'Sorriso', "position": 'FW'},
            {"number": 11, "name": 'Óscar Aranda', "position": 'FW'},
        ],
    },
    {
        "id": 'gil_vicente',
        "name": 'Gil Vicente',
        "kits": [
            {"name": 'Home', "pattern": 'solid', "colors": [(173, 24, 20), (56, 136, 183)]},
            {"name": 'Away', "pattern": 'solid', "colors": [(255, 255, 255), (173, 24, 20)]},
            {"name": 'Third', "pattern": 'solid', "colors": [(194, 167, 207)]},
        ],
        "gk_kit": {"name": 'GK', "pattern": 'solid', "colors": [(240, 196, 25)]},
        "squad": [
            {"number": 1, "name": 'André Picornell', "position": 'GK'},
            {"number": 30, "name": 'Lucão', "position": 'GK'},
            {"number": 42, "name": 'Andrew Ventura', "position": 'GK'},
            {"number": 99, "name": 'Dani Figueira', "position": 'GK'},
            {"number": 26, "name": 'Weverson Costa', "position": 'DF'},
            {"number": 2, "name": 'Zé Carlos', "position": 'DF'},
            {"number": 20, "name": 'Hevertton Santos', "position": 'DF'},
            {"number": 4, "name": 'Marvin Elimbi', "position": 'DF'},
            {"number": 28, "name": 'Diogo Costa', "position": 'DF'},
            {"number": 39, "name": 'Jonathan Buatu', "position": 'DF'},
            {"number": 48, "name": 'Antonio Espigares', "position": 'DF'},
            {"number": 59, "name": 'Arthur Tchaptchet', "position": 'DF'},
            {"number": 3, "name": 'Ghislain Konan', "position": 'DF'},
            {"number": 45, "name": 'Jonathan Mutombo', "position": 'DF'},
            {"number": 16, "name": 'Gui Beleza', "position": 'MF'},
            {"number": 23, "name": 'Guilherme Freitas', "position": 'MF'},
            {"number": 8, "name": 'Mohamed Bamba', "position": 'MF'},
            {"number": 5, "name": 'Facundo Cáseres', "position": 'MF'},
            {"number": 6, "name": 'Zé Carlos', "position": 'MF'},
            {"number": 10, "name": 'Luís Esteves', "position": 'MF'},
            {"number": 19, "name": 'Gil Martins', "position": 'MF'},
            {"number": 82, "name": 'Gonçalo Maia', "position": 'MF'},
            {"number": 95, "name": 'Santi García', "position": 'MF'},
            {"number": 7, "name": 'Tidjany Touré', "position": 'FW'},
            {"number": 29, "name": 'Carlos Eduardo', "position": 'FW'},
            {"number": 17, "name": 'Sergio Bermejo', "position": 'FW'},
            {"number": 77, "name": 'Murilo Souza', "position": 'FW'},
            {"number": 80, "name": 'Rodrigo Rodrigues', "position": 'FW'},
            {"number": 89, "name": 'Gustavo Varela', "position": 'FW'},
            {"number": 9, "name": 'Pablo Felipe', "position": 'FW'},
            {"number": 23, "name": 'Héctor Hernández', "position": 'FW'},
            {"number": 11, "name": 'Joelson Fernandes', "position": 'FW'},
            {"number": 27, "name": 'Agustín Moreira', "position": 'FW'},
            {"number": 32, "name": 'Martín Fernández', "position": 'FW'},
        ],
    },
    {
        "id": 'moreirense',
        "name": 'Moreirense',
        "kits": [
            {"name": 'Home', "pattern": 'solid', "colors": [(255, 255, 255)]},
            {"name": 'Away', "pattern": 'solid', "colors": [(255, 136, 0)]},
            {"name": 'Third', "pattern": 'solid', "colors": [(29, 29, 47), (47, 49, 43)]},
        ],
        "gk_kit": {"name": 'GK', "pattern": 'solid', "colors": [(240, 196, 25)]},
        "squad": [
            {"number": 16, "name": 'Mika', "position": 'GK'},
            {"number": 13, "name": 'André Ferreira', "position": 'GK'},
            {"number": 22, "name": 'Caio Secco', "position": 'GK'},
            {"number": 3, "name": 'Michel', "position": 'DF'},
            {"number": 17, "name": 'Álvaro Martínez', "position": 'DF'},
            {"number": 66, "name": 'Gilberto Batista', "position": 'DF'},
            {"number": 70, "name": 'Fabiano Souza', "position": 'DF'},
            {"number": 2, "name": 'Diogo Travassos', "position": 'DF'},
            {"number": 71, "name": 'Leandro Santos', "position": 'DF'},
            {"number": 76, "name": 'Dinis Pinto', "position": 'DF'},
            {"number": 4, "name": 'Kevyn', "position": 'DF'},
            {"number": 26, "name": 'Maracás', "position": 'DF'},
            {"number": 44, "name": 'Marcelo', "position": 'DF'},
            {"number": 27, "name": 'Francisco Domingues', "position": 'DF'},
            {"number": 23, "name": 'Nile John', "position": 'MF'},
            {"number": 8, "name": 'Mateja Stjepanović', "position": 'MF'},
            {"number": 25, "name": 'Afonso Assis', "position": 'MF'},
            {"number": 6, "name": 'Miguel Silva', "position": 'MF'},
            {"number": 15, "name": 'Vasco Sousa', "position": 'MF'},
            {"number": 21, "name": 'Rodrigo Alonso', "position": 'MF'},
            {"number": 30, "name": 'Jimi Gower', "position": 'MF'},
            {"number": 11, "name": 'Alan', "position": 'MF'},
            {"number": 20, "name": 'Benny', "position": 'MF'},
            {"number": 80, "name": 'Lawrence Ofori', "position": 'MF'},
            {"number": 95, "name": 'Guilherme Schettine', "position": 'FW'},
            {"number": 7, "name": 'Cédric Teguia', "position": 'FW'},
            {"number": 9, "name": 'Luís Hemir', "position": 'FW'},
            {"number": 99, "name": 'Yan Lincon', "position": 'FW'},
            {"number": 10, "name": 'Kiko Bondoso', "position": 'FW'},
            {"number": 19, "name": 'Joel Jorquera', "position": 'FW'},
            {"number": 78, "name": 'Landerson', "position": 'FW'},
        ],
    },
    {
        "id": 'fc_arouca',
        "name": 'FC Arouca',
        "kits": [
            {"name": 'Home', "pattern": 'solid', "colors": [(253, 217, 69), (45, 76, 151)]},
            {"name": 'Away', "pattern": 'solid', "colors": [(255, 255, 255), (243, 3, 21)]},
        ],
        "gk_kit": {"name": 'GK', "pattern": 'solid', "colors": [(240, 196, 25)]},
        "squad": [
            {"number": 1, "name": 'João Valido', "position": 'GK'},
            {"number": 12, "name": 'Ignacio de Arruabarrena', "position": 'GK'},
            {"number": 30, "name": 'Jakub Vinarcik', "position": 'GK'},
            {"number": 58, "name": 'Nico Mantl', "position": 'GK'},
            {"number": 2, "name": 'José Silva', "position": 'DF'},
            {"number": 28, "name": 'Tiago Esgaio', "position": 'DF'},
            {"number": 78, "name": 'Alex Pinto', "position": 'DF'},
            {"number": 66, "name": 'Omar Fayed', "position": 'DF'},
            {"number": 4, "name": 'Matías Rocha', "position": 'DF'},
            {"number": 5, "name": 'Boris Popović', "position": 'DF'},
            {"number": 6, "name": 'Diogo Monteiro', "position": 'DF'},
            {"number": 15, "name": 'Javi Sánchez', "position": 'DF'},
            {"number": 3, "name": 'Jose Fontán', "position": 'DF'},
            {"number": 16, "name": 'Arnau Solà', "position": 'DF'},
            {"number": 25, "name": 'Bas Kuipers', "position": 'DF'},
            {"number": 44, "name": 'Amadou Danté', "position": 'DF'},
            {"number": 6, "name": 'Mamadou Loum', "position": 'MF'},
            {"number": 20, "name": 'Yellu Santiago', "position": 'MF'},
            {"number": 85, "name": 'Gui Rodrigues', "position": 'MF'},
            {"number": 8, "name": 'David Simão', "position": 'MF'},
            {"number": 21, "name": 'Taichi Fukui', "position": 'MF'},
            {"number": 22, "name": 'Espen van Ee', "position": 'MF'},
            {"number": 46, "name": 'Mateo Flores', "position": 'MF'},
            {"number": 10, "name": 'Pablo Gozálbez', "position": 'MF'},
            {"number": 14, "name": 'Lee Hyunju', "position": 'MF'},
            {"number": 89, "name": 'Pedro Santos', "position": 'MF'},
            {"number": 9, "name": 'Uladzislau Marozau', "position": 'FW'},
            {"number": 9, "name": 'Fally Mayulu', "position": 'FW'},
            {"number": 17, "name": 'Barbero', "position": 'FW'},
            {"number": 23, "name": 'Dylan Nandín', "position": 'FW'},
            {"number": 77, "name": 'Romualdas Jansonas', "position": 'FW'},
            {"number": 87, "name": 'Batata', "position": 'FW'},
            {"number": 7, "name": 'Naïs Djouahra', "position": 'FW'},
            {"number": 11, "name": 'Miguel Puche', "position": 'FW'},
            {"number": 19, "name": 'Alfonso Trezza', "position": 'FW'},
            {"number": 24, "name": 'Brian Mansilla', "position": 'FW'},
        ],
    },
    {
        "id": 'vit_ria_sc',
        "name": 'Vitória SC',
        "kits": [
            {"name": 'Home', "pattern": 'solid', "colors": [(255, 255, 255), (0, 0, 0)]},
            {"name": 'Away', "pattern": 'solid', "colors": [(0, 0, 0), (229, 228, 226)]},
            {"name": 'Third', "pattern": 'solid', "colors": [(243, 150, 21), (76, 80, 95)]},
        ],
        "gk_kit": {"name": 'GK', "pattern": 'solid', "colors": [(240, 196, 25)]},
        "squad": [
            {"number": 25, "name": 'Juan Castillo', "position": 'GK'},
            {"number": 27, "name": 'Charles Silva', "position": 'GK'},
            {"number": 91, "name": 'José Ribeiro', "position": 'GK'},
            {"number": 98, "name": 'Lucas Furtado', "position": 'GK'},
            {"number": 2, "name": 'Miguel Maga', "position": 'DF'},
            {"number": 66, "name": 'Tony Strata', "position": 'DF'},
            {"number": 3, "name": 'Miguel Nóbrega', "position": 'DF'},
            {"number": 4, "name": 'Óscar Rivas', "position": 'DF'},
            {"number": 5, "name": 'Paulo Vitor', "position": 'DF'},
            {"number": 24, "name": 'Toni Borevkovic', "position": 'DF'},
            {"number": 26, "name": 'Rodrigo Abascal', "position": 'DF'},
            {"number": 28, "name": 'Thiago Balieiro', "position": 'DF'},
            {"number": 75, "name": 'André Oliveira', "position": 'DF'},
            {"number": 13, "name": 'João Mendes', "position": 'DF'},
            {"number": 17, "name": 'Orest Lebedenko', "position": 'DF'},
            {"number": 82, "name": 'Francisco Dias', "position": 'DF'},
            {"number": 46, "name": 'Hugo Nunes', "position": 'MF'},
            {"number": 80, "name": 'Ricardo Rocha', "position": 'MF'},
            {"number": 23, "name": 'Diogo Sousa', "position": 'MF'},
            {"number": 6, "name": 'Matija Mitrovic', "position": 'MF'},
            {"number": 8, "name": 'Tomás Händel', "position": 'MF'},
            {"number": 10, "name": 'Tiago Silva', "position": 'MF'},
            {"number": 16, "name": 'Beni Mukendi', "position": 'MF'},
            {"number": 30, "name": 'Gonçalo Nogueira', "position": 'MF'},
            {"number": 20, "name": 'Samu Silva', "position": 'MF'},
            {"number": 50, "name": 'Zeega', "position": 'MF'},
            {"number": 88, "name": 'Miguel Nogueira', "position": 'MF'},
            {"number": 11, "name": 'Gustavo Silva', "position": 'FW'},
            {"number": 14, "name": 'Rodrigo Duarte', "position": 'FW'},
            {"number": 18, "name": 'Telmo Arcanjo', "position": 'FW'},
            {"number": 87, "name": 'Guilherme Paula', "position": 'FW'},
            {"number": 7, "name": 'Nélson Oliveira', "position": 'FW'},
            {"number": 33, "name": 'Ejike Opara', "position": 'FW'},
            {"number": 90, "name": 'Alioune Ndoye', "position": 'FW'},
            {"number": 19, "name": 'Oumar Camara', "position": 'FW'},
            {"number": 21, "name": 'Vando Félix', "position": 'FW'},
            {"number": 22, "name": 'Fabio Blanco', "position": 'FW'},
            {"number": 48, "name": 'Noah Saviolo', "position": 'FW'},
            {"number": 77, "name": 'Nuno Santos', "position": 'FW'},
        ],
    },
    {
        "id": 'estoril_praia',
        "name": 'Estoril Praia',
        "kits": [
            {"name": 'Home', "pattern": 'solid', "colors": [(253, 217, 69), (39, 62, 124)]},
            {"name": 'Away', "pattern": 'solid', "colors": [(0, 36, 91), (254, 196, 0)]},
        ],
        "gk_kit": {"name": 'GK', "pattern": 'solid', "colors": [(240, 196, 25)]},
        "squad": [
            {"number": 31, "name": 'Diogo Dias', "position": 'GK'},
            {"number": 98, "name": 'Fletcher Lowe', "position": 'GK'},
            {"number": 1, "name": 'Joel Robles', "position": 'GK'},
            {"number": 16, "name": 'Martin Turk', "position": 'GK'},
            {"number": 18, "name": 'Or Israelov', "position": 'DF'},
            {"number": 20, "name": 'Gonçalo Costa', "position": 'DF'},
            {"number": 24, "name": 'Pedro Amaral', "position": 'DF'},
            {"number": 82, "name": 'Pedro Andrade', "position": 'DF'},
            {"number": 2, "name": 'Ricard Sánchez', "position": 'DF'},
            {"number": 72, "name": 'Júlio Gil', "position": 'DF'},
            {"number": 22, "name": 'Pedro Carvalho', "position": 'DF'},
            {"number": 4, "name": 'Ferro', "position": 'DF'},
            {"number": 5, "name": 'Antef Tsoungui', "position": 'DF'},
            {"number": 25, "name": 'Felix Bacher', "position": 'DF'},
            {"number": 44, "name": 'Kévin Boma', "position": 'DF'},
            {"number": 57, "name": 'Longin Bimai', "position": 'DF'},
            {"number": 17, "name": 'Fabrício Garcia', "position": 'DF'},
            {"number": 55, "name": 'Tiago Parente', "position": 'DF'},
            {"number": 91, "name": 'Jan Montes', "position": 'DF'},
            {"number": 6, "name": 'Jandro Orellana', "position": 'MF'},
            {"number": 10, "name": 'Jordan Holsgrove', "position": 'MF'},
            {"number": 45, "name": 'Patrick de Paula', "position": 'MF'},
            {"number": 90, "name": 'Tiago Brito', "position": 'MF'},
            {"number": 7, "name": 'Nodar Lominadze', "position": 'MF'},
            {"number": 8, "name": 'Xeka', "position": 'MF'},
            {"number": 21, "name": 'Pizzi', "position": 'MF'},
            {"number": 79, "name": 'Bernardo Lourenço', "position": 'MF'},
            {"number": 12, "name": 'João Carvalho', "position": 'MF'},
            {"number": 19, "name": 'André Lacximicant', "position": 'FW'},
            {"number": 99, "name": 'Rafik Guitane', "position": 'FW'},
            {"number": 70, "name": 'Peixinho', "position": 'FW'},
            {"number": 9, "name": 'Alejandro Marqués', "position": 'FW'},
            {"number": 11, "name": 'Khayon Edwards', "position": 'FW'},
            {"number": 14, "name": 'Yanis Begraoui', "position": 'FW'},
            {"number": 48, "name": 'Kelian Baruti', "position": 'FW'},
            {"number": 97, "name": 'Luís Gomes', "position": 'FW'},
        ],
    },
    {
        "id": 'fc_alverca',
        "name": 'FC Alverca',
        "kits": [
            {"name": 'Home', "pattern": 'solid', "colors": [(255, 255, 255)]},
        ],
        "gk_kit": {"name": 'GK', "pattern": 'solid', "colors": [(240, 196, 25)]},
        "squad": [
            {"number": 1, "name": 'Mateus', "position": 'GK'},
            {"number": 1, "name": 'Cristian', "position": 'GK'},
            {"number": 13, "name": 'André Gomes', "position": 'GK'},
            {"number": 23, "name": 'André Paulo', "position": 'GK'},
            {"number": 31, "name": 'Matheus Mendes', "position": 'GK'},
            {"number": 2, "name": 'Nabil Touaizi', "position": 'DF'},
            {"number": 22, "name": 'Gonçalo Esteves', "position": 'DF'},
            {"number": 37, "name": 'Kauan Gomes', "position": 'DF'},
            {"number": 82, "name": 'Diogo Spencer', "position": 'DF'},
            {"number": 4, "name": 'Kaiky Naves', "position": 'DF'},
            {"number": 36, "name": 'Gonçalo Silva', "position": 'DF'},
            {"number": 3, "name": 'Julián Martínez', "position": 'DF'},
            {"number": 5, "name": 'Sergi Gómez', "position": 'DF'},
            {"number": 14, "name": 'Steven Baseya', "position": 'DF'},
            {"number": 33, "name": 'Bastien Meupiyou', "position": 'DF'},
            {"number": 34, "name": 'Talisca', "position": 'DF'},
            {"number": 78, "name": 'Lamine Ndiaye', "position": 'DF'},
            {"number": 96, "name": 'Rodrigo Dias', "position": 'DF'},
            {"number": 98, "name": 'Fabrício Garcia', "position": 'DF'},
            {"number": 12, "name": 'Isaac James', "position": 'DF'},
            {"number": 15, "name": 'Ikker Julian', "position": 'DF'},
            {"number": 55, "name": 'Francisco Chissumba', "position": 'DF'},
            {"number": 16, "name": 'Tomás Mendes', "position": 'MF'},
            {"number": 21, "name": 'Sabit Abdulai', "position": 'MF'},
            {"number": 28, "name": 'Gian Cabezas', "position": 'MF'},
            {"number": 30, "name": 'Abderrahmane Soumaré', "position": 'MF'},
            {"number": 26, "name": 'Rhaldney', "position": 'MF'},
            {"number": 6, "name": 'Davy Gui', "position": 'MF'},
            {"number": 8, "name": 'Alex Amorim', "position": 'MF'},
            {"number": 17, "name": 'Vasco Moreira', "position": 'MF'},
            {"number": 35, "name": 'Zakaria Kessary', "position": 'MF'},
            {"number": 88, "name": 'Diogo Martins', "position": 'MF'},
            {"number": 38, "name": 'Hugo Martins', "position": 'MF'},
            {"number": 18, "name": 'Lincoln', "position": 'MF'},
            {"number": 25, "name": 'Stéphane Diarra', "position": 'FW'},
            {"number": 19, "name": 'Mathis Clairicia', "position": 'FW'},
            {"number": 91, "name": 'Sandro Lima', "position": 'FW'},
            {"number": 9, "name": 'Marezi', "position": 'FW'},
            {"number": 19, "name": 'Tiago Leite', "position": 'FW'},
            {"number": 77, "name": 'Felipe Lima', "position": 'FW'},
            {"number": 7, "name": 'Léo Chú', "position": 'FW'},
            {"number": 10, "name": 'Chiquinho', "position": 'FW'},
            {"number": 11, "name": 'Cédric Nuozzi', "position": 'FW'},
            {"number": 17, "name": 'Junior Mendes', "position": 'FW'},
            {"number": 20, "name": 'Figueiredo', "position": 'FW'},
        ],
    },
    {
        "id": 'rio_ave',
        "name": 'Rio Ave',
        "kits": [
            {"name": 'Home', "pattern": 'vertical-3-stripes_1_col-2', "colors": [(52, 124, 23), (229, 228, 226)]},
        ],
        "gk_kit": {"name": 'GK', "pattern": 'solid', "colors": [(240, 196, 25)]},
        "squad": [
            {"number": 13, "name": 'Pedro Virgínia', "position": 'GK'},
            {"number": 1, "name": 'Cezary Miszta', "position": 'GK'},
            {"number": 22, "name": 'Kevin Chamorro', "position": 'GK'},
            {"number": 29, "name": 'Alfonso Pastor', "position": 'GK'},
            {"number": 99, "name": 'Ennio van der Gouw', "position": 'GK'},
            {"number": 77, "name": 'Omar Richards', "position": 'DF'},
            {"number": 2, "name": 'Eric Moreira', "position": 'DF'},
            {"number": 17, "name": 'Marious Vrousai', "position": 'DF'},
            {"number": 20, "name": 'João Tomé', "position": 'DF'},
            {"number": 6, "name": 'Nelson Abbey', "position": 'DF'},
            {"number": 39, "name": 'Gustavo Mancha', "position": 'DF'},
            {"number": 4, "name": 'Jonathan Panzo', "position": 'DF'},
            {"number": 5, "name": 'Andreas Ntoi', "position": 'DF'},
            {"number": 23, "name": 'Pancho Petrasso', "position": 'DF'},
            {"number": 32, "name": 'Jakub Brabec', "position": 'DF'},
            {"number": 63, "name": 'Julien Lomboto', "position": 'DF'},
            {"number": 24, "name": 'Leonardo Buta', "position": 'DF'},
            {"number": 3, "name": 'Nikos Athanasiou', "position": 'DF'},
            {"number": 8, "name": 'Theofanis Bakoulas', "position": 'MF'},
            {"number": 44, "name": 'Tamás Nikitscher', "position": 'MF'},
            {"number": 54, "name": 'Georgios Liavas', "position": 'MF'},
            {"number": 21, "name": 'João Graça', "position": 'MF'},
            {"number": 8, "name": 'Ryan Guilherme', "position": 'MF'},
            {"number": 19, "name": 'Antonis Papakanellos', "position": 'MF'},
            {"number": 7, "name": 'João Novais', "position": 'MF'},
            {"number": 10, "name": 'Brandon Aguilera', "position": 'MF'},
            {"number": 14, "name": 'Karem Zoabi', "position": 'FW'},
            {"number": 25, "name": 'Rafael Lobato', "position": 'FW'},
            {"number": 27, "name": 'Tobías Medina', "position": 'FW'},
            {"number": 11, "name": 'André Luiz', "position": 'FW'},
            {"number": 18, "name": 'Dario Spikic', "position": 'FW'},
            {"number": 9, "name": 'Tamble Monteiro', "position": 'FW'},
            {"number": 9, "name": 'Clayton Silva', "position": 'FW'},
            {"number": 11, "name": 'Jalen Blesa', "position": 'FW'},
            {"number": 28, "name": 'Marc Gual', "position": 'FW'},
            {"number": 73, "name": 'Naziru Shuabiu', "position": 'FW'},
            {"number": 7, "name": 'Diogo Bezerra', "position": 'FW'},
            {"number": 80, "name": 'Ole Pohlmann', "position": 'FW'},
        ],
    },
    {
        "id": 'santa_clara',
        "name": 'Santa Clara',
        "kits": [
            {"name": 'Home', "pattern": 'solid', "colors": [(173, 24, 20), (229, 228, 226)]},
            {"name": 'Away', "pattern": 'solid', "colors": [(19, 35, 78), (229, 228, 226)]},
        ],
        "gk_kit": {"name": 'GK', "pattern": 'solid', "colors": [(240, 196, 25)]},
        "squad": [
            {"number": 25, "name": 'Cristian', "position": 'GK'},
            {"number": 1, "name": 'Gabriel Batista', "position": 'GK'},
            {"number": 12, "name": 'Neneca', "position": 'GK'},
            {"number": 31, "name": 'Denivys', "position": 'GK'},
            {"number": 50, "name": 'João Afonso', "position": 'GK'},
            {"number": 85, "name": 'José Franco', "position": 'DF'},
            {"number": 42, "name": 'Lucas Soares', "position": 'DF'},
            {"number": 2, "name": 'Diogo Calila', "position": 'DF'},
            {"number": 22, "name": 'Edney Silva', "position": 'DF'},
            {"number": 4, "name": 'Pedro Pacheco', "position": 'DF'},
            {"number": 21, "name": 'Frederico Venâncio', "position": 'DF'},
            {"number": 93, "name": 'Italo Cabelinho', "position": 'DF'},
            {"number": 94, "name": 'Henrique Silva', "position": 'DF'},
            {"number": 13, "name": 'Luís Rocha', "position": 'DF'},
            {"number": 23, "name": 'Sidney Lima', "position": 'DF'},
            {"number": 24, "name": 'Rodrigo Mendes', "position": 'DF'},
            {"number": 44, "name": 'Marcos Victor', "position": 'DF'},
            {"number": 97, "name": 'Danilo Lucas', "position": 'DF'},
            {"number": 5, "name": 'Guilherme Romão', "position": 'DF'},
            {"number": 3, "name": 'Matheus Pereira', "position": 'DF'},
            {"number": 32, "name": 'MT', "position": 'DF'},
            {"number": 64, "name": 'Paulo Victor', "position": 'DF'},
            {"number": 82, "name": 'Luiz Otávio', "position": 'MF'},
            {"number": 77, "name": 'Gustavo Klismahn', "position": 'MF'},
            {"number": 6, "name": 'Adriano Firmino', "position": 'MF'},
            {"number": 8, "name": 'Pedro Ferreira', "position": 'MF'},
            {"number": 16, "name": 'Miguel Pires', "position": 'MF'},
            {"number": 52, "name": 'Isaac Valença', "position": 'MF'},
            {"number": 37, "name": 'Darlan Mendes', "position": 'MF'},
            {"number": 65, "name": 'Djé Tavares', "position": 'MF'},
            {"number": 76, "name": 'Tiago Queiroz', "position": 'MF'},
            {"number": 78, "name": 'Andrey', "position": 'MF'},
            {"number": 35, "name": 'Serginho', "position": 'MF'},
            {"number": 59, "name": 'Davis Silva', "position": 'MF'},
            {"number": 51, "name": 'Vital Maia', "position": 'FW'},
            {"number": 80, "name": 'Tiago Duarte', "position": 'FW'},
            {"number": 11, "name": 'Brenner Lucas', "position": 'FW'},
            {"number": 20, "name": 'Adriel Moraes', "position": 'FW'},
            {"number": 49, "name": 'Welinton Torrão', "position": 'FW'},
            {"number": 70, "name": 'Vinícius Lopes', "position": 'FW'},
            {"number": 26, "name": 'Fernando', "position": 'FW'},
            {"number": 7, "name": 'Elias Manoel', "position": 'FW'},
            {"number": 88, "name": 'Vitinho', "position": 'FW'},
            {"number": 9, "name": 'Anthony Carter', "position": 'FW'},
            {"number": 17, "name": 'João Costa', "position": 'FW'},
            {"number": 29, "name": 'Wendel Silva', "position": 'FW'},
            {"number": 39, "name": 'Gonçalo Paciência', "position": 'FW'},
            {"number": 69, "name": 'Melvin Costa', "position": 'FW'},
            {"number": 10, "name": 'Gabriel Silva', "position": 'FW'},
            {"number": 28, "name": 'Luquinhas', "position": 'FW'},
            {"number": 77, "name": 'Henrique Pereira', "position": 'FW'},
        ],
    },
    {
        "id": 'nacional',
        "name": 'Nacional',
        "kits": [
            {"name": 'Home', "pattern": 'vertical-3-stripes_1_col-2', "colors": [(16, 16, 16), (229, 228, 226)]},
            {"name": 'Away', "pattern": 'solid', "colors": [(213, 167, 0)]},
            {"name": 'Third', "pattern": 'solid', "colors": [(255, 255, 255)]},
        ],
        "gk_kit": {"name": 'GK', "pattern": 'solid', "colors": [(240, 196, 25)]},
        "squad": [
            {"number": 1, "name": 'Kaique Pereira', "position": 'GK'},
            {"number": 12, "name": 'César Augusto', "position": 'GK'},
            {"number": 37, "name": 'Lucas França', "position": 'GK'},
            {"number": 50, "name": 'Kevyn Vinícius', "position": 'GK'},
            {"number": 4, "name": 'Ulisses Wilson', "position": 'DF'},
            {"number": 33, "name": 'Chico Gonçalves', "position": 'DF'},
            {"number": 2, "name": 'João Aurélio', "position": 'DF'},
            {"number": 16, "name": 'Alan Nuñez', "position": 'DF'},
            {"number": 14, "name": 'Ivanildo Fernandes', "position": 'DF'},
            {"number": 34, "name": 'Léo Santos', "position": 'DF'},
            {"number": 38, "name": 'Zé Vitor', "position": 'DF'},
            {"number": 5, "name": 'José Gomes', "position": 'DF'},
            {"number": 24, "name": 'Lenny Vallier', "position": 'DF'},
            {"number": 22, "name": 'Filipe Soares', "position": 'MF'},
            {"number": 6, "name": 'Matheus Dias', "position": 'MF'},
            {"number": 28, "name": 'Igor Liziero', "position": 'MF'},
            {"number": 48, "name": 'Josué Souza', "position": 'MF'},
            {"number": 18, "name": 'André Sousa', "position": 'MF'},
            {"number": 20, "name": 'Jota Garcês', "position": 'MF'},
            {"number": 26, "name": 'Joel Silva', "position": 'MF'},
            {"number": 88, "name": 'Deivison', "position": 'MF'},
            {"number": 8, "name": 'Miguel Baeza', "position": 'MF'},
            {"number": 15, "name": 'Chiheb Labidi', "position": 'MF'},
            {"number": 10, "name": 'Daniel Júnior', "position": 'MF'},
            {"number": 30, "name": 'Martim Watts', "position": 'MF'},
            {"number": 17, "name": 'Mootaz Nourani', "position": 'FW'},
            {"number": 11, "name": 'Paulinho Bóia', "position": 'FW'},
            {"number": 99, "name": 'Pablo Ruan', "position": 'FW'},
            {"number": 9, "name": 'Chuchu Ramírez', "position": 'FW'},
            {"number": 19, "name": 'Lucas João', "position": 'FW'},
            {"number": 27, "name": 'Gabriel Veron', "position": 'FW'},
            {"number": 7, "name": 'Witi Quembo', "position": 'FW'},
        ],
    },
    {
        "id": 'est_amadora',
        "name": 'Est. Amadora',
        "kits": [
            {"name": 'Home', "pattern": 'vertical-3-stripes_2_col-2', "colors": [(128, 0, 32), (52, 124, 23)]},
            {"name": 'Away', "pattern": 'solid', "colors": [(0, 0, 0)]},
        ],
        "gk_kit": {"name": 'GK', "pattern": 'solid', "colors": [(240, 196, 25)]},
        "squad": [
            {"number": 40, "name": 'Renan Ribeiro', "position": 'GK'},
            {"number": 1, "name": 'Diogo Pinto', "position": 'GK'},
            {"number": 13, "name": 'Dudu', "position": 'GK'},
            {"number": 22, "name": 'David Grilo', "position": 'GK'},
            {"number": 17, "name": 'Jefferson Encada', "position": 'DF'},
            {"number": 21, "name": 'Max Scholze', "position": 'DF'},
            {"number": 55, "name": 'Sidny Cabral', "position": 'DF'},
            {"number": 3, "name": 'Ni Rodrigues', "position": 'DF'},
            {"number": 4, "name": 'Stefan Leković', "position": 'DF'},
            {"number": 4, "name": 'Semeu Commey', "position": 'DF'},
            {"number": 5, "name": 'Issiar Drame', "position": 'DF'},
            {"number": 14, "name": 'Bernardo Schappo', "position": 'DF'},
            {"number": 20, "name": 'Hamed Drame', "position": 'DF'},
            {"number": 23, "name": 'Georgii Tunguliiadi', "position": 'DF'},
            {"number": 30, "name": 'Luan Patrick', "position": 'DF'},
            {"number": 79, "name": 'Atanas Chernev', "position": 'DF'},
            {"number": 83, "name": 'Otávio', "position": 'DF'},
            {"number": 2, "name": 'Yahya Kalley', "position": 'DF'},
            {"number": 21, "name": 'Guilherme Montóia', "position": 'DF'},
            {"number": 24, "name": 'Bruno Langa', "position": 'DF'},
            {"number": 25, "name": 'Nilton Varela', "position": 'DF'},
            {"number": 66, "name": 'Ryan', "position": 'DF'},
            {"number": 12, "name": 'Tiago Pinto', "position": 'MF'},
            {"number": 6, "name": 'Kevin Jansson', "position": 'MF'},
            {"number": 39, "name": 'Eddy Doué', "position": 'MF'},
            {"number": 97, "name": 'Oumar Ngom', "position": 'MF'},
            {"number": 8, "name": 'Robinho', "position": 'MF'},
            {"number": 19, "name": 'Paulo Moreira', "position": 'MF'},
            {"number": 28, "name": 'Tom Moustier', "position": 'MF'},
            {"number": 63, "name": 'Alexandre Sola', "position": 'MF'},
            {"number": 18, "name": 'Jorge Meireles', "position": 'MF'},
            {"number": 26, "name": 'João Resende', "position": 'FW'},
            {"number": 26, "name": 'Billal Brahimi', "position": 'FW'},
            {"number": 89, "name": 'João Gastão', "position": 'FW'},
            {"number": 99, "name": 'Abraham Marcus', "position": 'FW'},
            {"number": 7, "name": 'Leandro Antonetti', "position": 'FW'},
            {"number": 9, "name": 'Rodrigo Pinho', "position": 'FW'},
            {"number": 13, "name": 'Alan Godoy', "position": 'FW'},
            {"number": 15, "name": 'Matthew Gbomadu', "position": 'FW'},
            {"number": 20, "name": 'Sydney van Hooijdonk', "position": 'FW'},
            {"number": 28, "name": 'Gonzalo Calsada', "position": 'FW'},
            {"number": 70, "name": 'Chilohem Onuoha', "position": 'FW'},
            {"number": 80, "name": 'Alisson Souza', "position": 'FW'},
            {"number": 98, "name": 'Kikas', "position": 'FW'},
            {"number": 7, "name": 'Fábio Ronaldo', "position": 'FW'},
            {"number": 10, "name": 'Ianis Stoica', "position": 'FW'},
            {"number": 11, "name": 'Jovane Cabral', "position": 'FW'},
            {"number": 87, "name": 'Simão Pedro', "position": 'FW'},
        ],
    },
    {
        "id": 'casa_pia_ac',
        "name": 'Casa Pia AC',
        "kits": [
            {"name": 'Home', "pattern": 'solid', "colors": [(16, 16, 16), (219, 181, 110)]},
            {"name": 'Away', "pattern": 'solid', "colors": [(255, 255, 255), (202, 168, 103)]},
        ],
        "gk_kit": {"name": 'GK', "pattern": 'solid', "colors": [(240, 196, 25)]},
        "squad": [
            {"number": 31, "name": 'Rodrigo Moura', "position": 'GK'},
            {"number": 33, "name": 'Ricardo Batista', "position": 'GK'},
            {"number": 1, "name": 'Patrick Sequeira', "position": 'GK'},
            {"number": 22, "name": 'Daniel Azevedo', "position": 'GK'},
            {"number": 95, "name": 'Ivan Mandić', "position": 'GK'},
            {"number": 72, "name": 'Gaizka Larrazabal', "position": 'DF'},
            {"number": 18, "name": 'André Geraldes', "position": 'DF'},
            {"number": 6, "name": 'José Fonte', "position": 'DF'},
            {"number": 2, "name": 'Duplexe Tchamba', "position": 'DF'},
            {"number": 3, "name": 'Khaly', "position": 'DF'},
            {"number": 4, "name": 'João Goulart', "position": 'DF'},
            {"number": 27, "name": 'Kaique Rocha', "position": 'DF'},
            {"number": 43, "name": 'David Sousa', "position": 'DF'},
            {"number": 75, "name": 'Pedro Rosas', "position": 'DF'},
            {"number": 5, "name": 'Abdu Conté', "position": 'DF'},
            {"number": 12, "name": 'Fahem Benaissa', "position": 'DF'},
            {"number": 59, "name": 'Abdu Dafe', "position": 'MF'},
            {"number": 8, "name": 'Rafael Brito', "position": 'MF'},
            {"number": 24, "name": 'Iyad Mohamed', "position": 'MF'},
            {"number": 42, "name": 'Sebastián Pérez', "position": 'MF'},
            {"number": 14, "name": 'Miguel Sousa', "position": 'MF'},
            {"number": 20, "name": 'Yassin Oukili', "position": 'MF'},
            {"number": 74, "name": 'Renato Nhaga', "position": 'MF'},
            {"number": 80, "name": 'Lawrence Ofori', "position": 'MF'},
            {"number": 17, "name": 'Xander Severina', "position": 'FW'},
            {"number": 13, "name": 'Korede Osundina', "position": 'FW'},
            {"number": 19, "name": 'Kevin Prieto', "position": 'FW'},
            {"number": 58, "name": 'Miguel Neves', "position": 'FW'},
            {"number": 90, "name": 'Cassiano', "position": 'FW'},
            {"number": 99, "name": 'Clau Mendes', "position": 'FW'},
            {"number": 9, "name": 'Max Svensson', "position": 'FW'},
            {"number": 10, "name": 'Dailon Livramento', "position": 'FW'},
            {"number": 11, "name": 'João Marques', "position": 'FW'},
            {"number": 21, "name": 'Tiago Morais', "position": 'FW'},
            {"number": 7, "name": 'Kelian Nsona', "position": 'FW'},
            {"number": 29, "name": 'Jérémy Livolant', "position": 'FW'},
            {"number": 32, "name": 'Kiki Silva', "position": 'FW'},
        ],
    },
    {
        "id": 'cd_tondela',
        "name": 'CD Tondela',
        "kits": [
            {"name": 'Home', "pattern": 'solid', "colors": [(251, 235, 0)]},
            {"name": 'Away', "pattern": 'solid', "colors": [(0, 0, 0)]},
        ],
        "gk_kit": {"name": 'GK', "pattern": 'solid', "colors": [(240, 196, 25)]},
        "squad": [
            {"number": 1, "name": 'Gabriel Souza', "position": 'GK'},
            {"number": 30, "name": 'Lucas Cañizares', "position": 'GK'},
            {"number": 31, "name": 'Bernardo Fontes', "position": 'GK'},
            {"number": 48, "name": 'Tiago Manso', "position": 'DF'},
            {"number": 2, "name": 'Bebeto', "position": 'DF'},
            {"number": 27, "name": 'Rodrigo Conceição', "position": 'DF'},
            {"number": 20, "name": 'Brayan Medina', "position": 'DF'},
            {"number": 44, "name": 'João Silva', "position": 'DF'},
            {"number": 3, "name": 'Diego Tavares', "position": 'DF'},
            {"number": 4, "name": 'Christian Marques', "position": 'DF'},
            {"number": 5, "name": 'João Afonso', "position": 'DF'},
            {"number": 60, "name": 'Nor Maviram', "position": 'DF'},
            {"number": 21, "name": 'Rémy Vita', "position": 'DF'},
            {"number": 32, "name": 'Juan Rodríguez', "position": 'MF'},
            {"number": 6, "name": 'André Ceitil', "position": 'MF'},
            {"number": 10, "name": 'Joe Hodge', "position": 'MF'},
            {"number": 15, "name": 'Yaya Sithole', "position": 'MF'},
            {"number": 8, "name": 'Hélder Tavares', "position": 'MF'},
            {"number": 97, "name": 'Cícero Alves', "position": 'MF'},
            {"number": 14, "name": 'Xabi Huarte', "position": 'MF'},
            {"number": 79, "name": 'Hugo Félix', "position": 'MF'},
            {"number": 70, "name": 'Ouattara Moudjatovic', "position": 'FW'},
            {"number": 16, "name": 'Rony Lopes', "position": 'FW'},
            {"number": 19, "name": 'Afonso Rodrigues', "position": 'FW'},
            {"number": 26, "name": 'Arjen van der Heide', "position": 'FW'},
            {"number": 9, "name": 'Miro', "position": 'FW'},
            {"number": 11, "name": 'Yefrei Rodríguez', "position": 'FW'},
            {"number": 29, "name": 'Jordan Siebatcheu', "position": 'FW'},
            {"number": 23, "name": 'Benjamin Kimpioka', "position": 'FW'},
            {"number": 7, "name": 'Pedro Maranhão', "position": 'FW'},
            {"number": 17, "name": 'Ivan Cavaleiro', "position": 'FW'},
            {"number": 67, "name": 'Yarlen', "position": 'FW'},
            {"number": 90, "name": 'Makan Aïko', "position": 'FW'},
        ],
    },
    {
        "id": 'afs',
        "name": 'AFS',
        "kits": [
            {"name": 'Home', "pattern": 'vertical-3-stripes_2_col-2', "colors": [(173, 24, 20), (255, 255, 255)]},
            {"name": 'Away', "pattern": 'solid', "colors": [(115, 255, 0)]},
        ],
        "gk_kit": {"name": 'GK', "pattern": 'solid', "colors": [(240, 196, 25)]},
        "squad": [
            {"number": 1, "name": 'Adriel Ramos', "position": 'GK'},
            {"number": 88, "name": 'Pedro Trigueira', "position": 'GK'},
            {"number": 93, "name": 'Simão Bertelli', "position": 'GK'},
            {"number": 99, "name": 'João Gonçalves', "position": 'GK'},
            {"number": 64, "name": 'Afonso Silva', "position": 'DF'},
            {"number": 2, "name": 'Diogo Spencer', "position": 'DF'},
            {"number": 4, "name": 'Sidi Bane', "position": 'DF'},
            {"number": 5, "name": 'Guillem Molina', "position": 'DF'},
            {"number": 97, "name": 'Mateus Pivô', "position": 'DF'},
            {"number": 3, "name": 'Paulo Vitor', "position": 'DF'},
            {"number": 26, "name": 'Carlos Ponck', "position": 'DF'},
            {"number": 33, "name": 'Aderllan Santos', "position": 'DF'},
            {"number": 35, "name": 'Rúben Semedo', "position": 'DF'},
            {"number": 6, "name": 'Baptiste Roux', "position": 'DF'},
            {"number": 42, "name": 'Cristian Devenish', "position": 'DF'},
            {"number": 24, "name": 'Kiki Afonso', "position": 'DF'},
            {"number": 12, "name": 'Leonardo Rivas', "position": 'DF'},
            {"number": 6, "name": 'Gustavo Assunção', "position": 'MF'},
            {"number": 15, "name": 'Jaume Grau', "position": 'MF'},
            {"number": 19, "name": 'Tiago Galletto', "position": 'MF'},
            {"number": 23, "name": 'Gustavo Mendonça', "position": 'MF'},
            {"number": 27, "name": 'Ángel Algobia', "position": 'MF'},
            {"number": 70, "name": 'Roni Moura', "position": 'MF'},
            {"number": 8, "name": 'Pedro Lima', "position": 'MF'},
            {"number": 17, "name": 'Bruno Lourenço', "position": 'MF'},
            {"number": 77, "name": 'António Machado', "position": 'MF'},
            {"number": 11, "name": 'Babatunde Akinsola', "position": 'FW'},
            {"number": 16, "name": 'Kobamelo Kodisang', "position": 'FW'},
            {"number": 21, "name": 'Guilherme Neiva', "position": 'FW'},
            {"number": 50, "name": 'Edson Mucuana', "position": 'FW'},
            {"number": 7, "name": 'Tomané', "position": 'FW'},
            {"number": 17, "name": 'Antoine Baroan', "position": 'FW'},
            {"number": 18, "name": 'Nenê', "position": 'FW'},
            {"number": 20, "name": 'Diego Duarte', "position": 'FW'},
            {"number": 9, "name": 'Jordi Escobar', "position": 'FW'},
            {"number": 14, "name": 'Óscar Perea', "position": 'FW'},
            {"number": 25, "name": 'Andre Green', "position": 'FW'},
            {"number": 10, "name": 'Rafael Barbosa', "position": 'FW'},
        ],
    },
]



def get_team(team_id):
    for t in TEAMS:
        if t["id"] == team_id:
            return t
    return None
